const custom_abilities_list = [
	//Abilities
	"shadow_shaman_mass_serpent_ward_lua",
	"shadow_shaman_shackles_lua",
	"medusa_split_shot_chc",
	"spectre_dispersion_lua",
	"tinker_rearm_custom",
	"spectre_haunt_lua",
	"dark_seer_wall_of_replica_lua",
	"terrorblade_reflection_lua",
	"chaos_knight_phantasm_lua",
	"elder_titan_echo_stomp_lua",
	"elder_titan_ancestral_spirit_lua",
	"elder_titan_natural_order_lua",
	"lina_fiery_soul",
	"undying_soul_rip",
	"undying_tombstone",
	//Items
	"item_blade_mail_lua",
	"item_tome_of_knowledge_lua",
];
